export const scamKeywords = [
  { word: "otp", score: 20 },
  { word: "urgent", score: 15 },
  { word: "immediately", score: 10 },
  { word: "verify", score: 12 },
  { word: "kyc", score: 15 },
  { word: "upi", score: 18 },
  { word: "qr", score: 10 },
  { word: "click", score: 8 },
  { word: "link", score: 8 },
  { word: "refund", score: 12 },
  { word: "bank account", score: 18 },
  { word: "password", score: 20 },
  { word: "reset password", score: 15 },
  { word: "blocked", score: 10 },
  { word: "suspended", score: 10 },
  { word: "congratulations", score: 8 },
  { word: "lottery", score: 12 },
  { word: "winner", score: 12 },
  { word: "investment", score: 10 },
  { word: "crypto", score: 10 },
  { word: "free", score: 6 },
  { word: "limited time", score: 8 },
  { word: "confirm", score: 10 },
  {word : "code" , score: 15},
  {word : "digit" , score: 15},
];
